project 'WanSheng.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WanSheng' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WanSheng

#    pod 'AFNetworking', '3.1.0'
#    pod 'SDWebImage', '3.8.1'
#    pod 'MJExtension','3.0.13'
#    pod 'MJRefresh','3.1.12'
   pod 'MBProgressHUD'
   pod 'Masonry'
   pod 'AFNetworking', '~> 3.1.0'
   pod 'YYCache', '~> 1.0.4'
pod 'SDCycleScrollView','~> 1.75'
pod 'IQKeyboardManager'
pod 'BaiduMapKit'
 pod 'IQActionSheetPickerView'
 pod 'JZLocationConverter'
 pod 'WechatOpenSDK'

end
